// flow-typed signature: 1c177925d0bf127b69cbabc47e32d3bf
// flow-typed version: <<STUB>>/babel-plugin-transform-optional-chaining_v^7.0.0-beta.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-optional-chaining'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-optional-chaining' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-optional-chaining/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-optional-chaining/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-optional-chaining/lib/index'>;
}
